# Matrix Operations

In [2]:
import numpy as np

In [31]:
a = np.array(([1, 2], [3, 4]))
b = np.array(([5, 6], [7, 8]))

#### 1. Read a matrix

In [37]:
m = int(input("No of rows:"))
n = int(input("No of columns:"))

# Read a 1D list of size m * n, convert it to a numpy array and reshape it into m x n
matrix = np.array([int(input()) for _ in range(m * n)]).reshape(m, n)
matrix

No of rows: 2
No of columns: 3
 1
 2
 3
 4
 5
 6


array([[1, 2, 3],
       [4, 5, 6]])

#### 2. Dot Product

In [33]:
# Element-wise multiplication
a.dot(b)

array([[19, 22],
       [43, 50]])

#### 3. Transpose

In [52]:
# Swap the rows and columns
a.transpose()         # a.T


array([[1, 3],
       [2, 4]])

#### 4. Flattened

In [58]:
# Convert 2D array to 1D array
a.flatten()

array([1, 2, 3, 4])

#### 5. Trace

In [61]:
# Sum of diagonal elements
a.trace()

5

#### 6. Rank

In [67]:
# Maximum number of linearly independent rows or columns (matrix's uniqueness score)
np.linalg.matrix_rank(a)

2

#### 7. Determinant

In [72]:
# Single number that reflects several important properties of the matrix
np.linalg.det(a)

-2.0000000000000004

#### 8. Inverse

In [77]:
# Matrix equivalent of a reciprocal, multiplying a matrix by its inverse gives you the identity matrix (undoes what the original matrix did)
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

#### 9. Eigenvalues and Eigenvectors

In [92]:
# Eigenvector is a direction that doesn’t change under the transformation, just stretches or shrinks. 
# Eigenvalue is how much it stretches or shrinks in that direction.

res = np.linalg.eig(a)
res

# res contains both eigenvalues and eigenvectors
# np.linalg.eig(a)[0] : Eigenbvalues
# np.linalg.eig(a)[1] : Eigenvectors

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [84]:
print("Eigenvalues:", res[0])
print("Eigenvectors:\n", res[1])

Eigen Values: [-0.37228132  5.37228132]
Eigen Vectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
