# NumPy
NumPy (**Numerical Python**) is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures efficiently.

In [7]:
import numpy as np

In [35]:
# Create 1D array
a = np.array([1, 2, 3, 4, 5])
print("1D array:", a)

# Create 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", b)

# Perform basic operations
sum_array = np.sum(a)
print("Sum of array:", sum_array)
mean_array = np.mean(a)
print("Mean of array:", mean_array)

# Perform element-wise addition
c = a + 10
print("Element-wise addition:", c)

# Matrix multiplication
d = np.dot(b, b.T)
print("Matrix Multiplication:\n", d)

# Broadcasting: Perform operations on 2 arrays with different shapes
e = b + a[:3]
print("Broadcasting:\n", e)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
Sum of array: 15
Mean of array: 3.0
Element-wise addition: [11 12 13 14 15]
Matrix Multiplication:
 [[14 32]
 [32 77]]
Broadcasting:
 [[2 4 6]
 [5 7 9]]


### 1. Element-wise comparison of two arrays

In [52]:
a1 = np.array([1, 2, 3])
a2 = np.array([5, 1, 3])

print("Array 1:", a1)
print("Array 2:", a2)

print("Greater:", np.greater(a1, a2))
print("Greater than or equal:", np.greater_equal(a1, a2))

print("Less:", np.less(a1, a2))
print("Less than or equal:", np.less_equal(a1, a2))

print("Equal:", np.equal(a1, a2))


Array 1: [1 2 3]
Array 2: [5 1 3]
Greater: [False  True False]
Greater than or equal: [False  True  True]
Less: [ True False False]
Less than or equal: [ True False  True]
Equal: [False False  True]


### 2. Array of all even integers from 30 to 70

In [63]:
np.arange(30, 71, 2)
# a = np.arange(30, 71, 2)
# print(a)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])